volumes:
  gslide-ai-generator-node-modules:

services:
  gslide-ai-generator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - gslide-ai-generator-node-modules:/app/node_modules
    ports:
      - "5173:5173"
